version: 1.0.{build}
image: Visual Studio 2015
configuration: Dev
#platform: Any CPU
shallow_clone: true
clone_folder: c:\projects\AppveyorEasy
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - nuget restore -DisableParallelProcessing c:\projects\AppveyorEasy\src\AppveyorEasy.sln
build:
  project: c:\projects\AppveyorEasy\src\AppveyorEasy.sln
  publish_wap: true